item {
  id: 1
  name: 'train'
}

item {
  id: 2
  name: 'motor'
}

item {
  id: 3
  name: 'bus'
}

item {
  id: 4
  name: 'rider'
}

item {
  id: 5
  name: 'bike'
}

item {
  id: 6
  name: 'traffic light'
}

item {
  id: 7
  name: 'traffic sign'
}

item {
  id: 8
  name: 'person'
}

item {
  id: 9
  name: 'truck'
}

item {
  id: 10
  name: 'car'
}

item {
  id: 11
  name: 'phone'
}
